dist: bionic
services:
  - xvfb
addons:
  apt:
    packages:
      - libgtk-3-dev
language: python
sudo: false
cache:
  pip: true
  directories:
  - eggs
  - downloads
python:
  - '3.7'
matrix:
  fast_finish: true
before_install:
  - export DISPLAY=:99.0
  - firefox -v
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
  - tar -xzf geckodriver-v0.20.1-linux64.tar.gz -C bin
  - export PATH=$(pwd)/bin:$PATH
  - virtualenv .
  - bin/pip install pathlib2
  - bin/pip3 install -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04/wxPython-4.0.6-cp37-cp37m-linux_x86_64.whl -vvv wxPython
  - bin/pip install --upgrade -r requirements.txt
install:
  - bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True annotate
  - bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True

script:
  - bin/code-analysis
  - bin/test
  - export ROBOTSUITE_PREFIX=ONLYROBOT && bin/test -t ONLYROBOT --all

after_success:
  - bin/createcoverage
  - bin/pip install coverage
  - bin/python -m coverage.pickle2json
  - pip install coveralls
  - coveralls
