dist: bionic
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - libgtk-3-dev
language: python
sudo: false
cache:
  pip: true
  directories:
  - eggs
  - downloads
python:
  - '3.7'
matrix:
  fast_finish: true
before_install:
  - wget "http://chromedriver.storage.googleapis.com/2.44/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - "export DISPLAY=:99.0"
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - virtualenv .
  - bin/pip install --upgrade -r requirements.txt
install:
  - bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True annotate
  - bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True

script:
  - bin/code-analysis
  - bin/test
  - export ROBOTSUITE_PREFIX=ONLYROBOT && bin/test -t ONLYROBOT --all

after_success:
  - bin/createcoverage
  - bin/pip install coverage
  - bin/python -m coverage.pickle2json
  - pip install coveralls
  - coveralls
