# -*- coding: utf-8 -*-
from collective.frontpage import _
from plone.app.registry.browser.controlpanel import ControlPanelFormWrapper
from plone.app.registry.browser.controlpanel import RegistryEditForm
from plone.z3cform import layout
from zope import schema
from zope.interface import Interface


class ISettings(Interface):

    section_colors = schema.List(
        title=_(u"frontpage_settings_section_colors_title", default="Section Colors"),
        value_type=schema.TextLine(),
        required=True,
        default=[
            u"None | rgba(0,0,0,0)",
            u"Plone Blue | #0083BE",
            u"Dirty White | #F5F5F5",
            u"Semi Transparent | rgba(0,0,0,0.5)",
            u"Alice Blue | #f0f8ff",
            u"Antique White | #faebd7",
            u"Aquamarine | #7fffd4",
            u"Azure | #f0ffff",
            u"Beige | #f5f5dc",
            u"Bisque | #ffe4c4",
            u"Black | #000000",
            u"Blanched Almond | #ffebcd",
            u"Blue | #0000ff",
            u"Blue Violet | #8a2be2",
            u"Brown | #a52a2a",
            u"Burly Wood | #deb887",
            u"Cadet Blue | #5f9ea0",
            u"Chartreuse | #7fff00",
            u"Chocolate | #d2691e",
            u"Coral | #ff7f50",
            u"Cornflower Blue | #6495ed",
            u"Cyan/Crimson/Aqua | #00ffff",
            u"Cornsilk | #fff8dc",
            u"Dark Blue | #00008b",
            u"Dark Cyan | #008b8b",
            u"Dark Golden Rod | #b8860b",
            u"Dark Grey | #a9a9a9",
            u"Dark Green | #006400",
            u"Dark Khaki | #bdb76b",
            u"Dark Magenta | #8b008b",
            u"Dark Olive Green | #556b2f",
            u"Dark Orange | #ff8c00",
            u"Dark Orchid | #9932cc",
            u"Dark Red | #8b0000",
            u"Dark Salmon | #e9967a",
            u"Dark Sea Green | #8fbc8f",
            u"Dark Slate Blue | #483d8b",
            u"Dark Slate Grey | #2f4f4f",
            u"Dark Turquoise | #00ced1",
            u"Dark Violet | #9400d3",
            u"Deep Pink | #ff1493",
            u"Deep Sky Blue | #00bfff",
            u"Dim Grey | #696969",
            u"Dodger Blue | #1e90ff",
            u"Firebrick | #b22222",
            u"Floral White | #fffaf0",
            u"Forest Green | #228b22",
            u"Gainsboro | #dcdcdc",
            u"Ghost White | #f8f8ff",
            u"Gold | #ffd700",
            u"Golden Rod | #daa520",
            u"Grey | #808080",
            u"Green | #008000",
            u"Green Yellow | #adff2f",
            u"Honeydew | #f0fff0",
            u"Hot Pink | #ff69b4",
            u"Indian Red | #cd5c5c",
            u"Indigo | #4b0082",
            u"Ivory | #fffff0",
            u"Khaki | #f0e68c",
            u"Lavender | #e6e6fa",
            u"Lavender Blush | #fff0f5",
            u"Lawn Green | #7cfc00",
            u"Lemon Chiffon | #fffacd",
            u"Light Blue | #add8e6",
            u"Light Coral | #f08080",
            u"Light Cyan | #e0ffff",
            u"Light Golden Rod Yellow | #fafad2",
            u"Light Green | #90ee90",
            u"Light Grey | #d3d3d3",
            u"Light Pink | #ffb6c1",
            u"Light Salmon | #ffa07a",
            u"Light Sea Green | #20b2aa",
            u"Light Sky Blue | #87cefa",
            u"Light Slate Grey | #778899",
            u"Light Steel Blue | #b0c4de",
            u"Light Yellow | #ffffe0",
            u"Lime | #00ff00",
            u"Lime Green | #32cd32",
            u"Linen2 | #faf0e6",
            u"Magenta/Fuchsia | #ff00ff",
            u"Maroon | #800000",
            u"Medium Aquamarine | #66cdaa",
            u"Medium Blue | #0000cd",
            u"Medium Orchid | #ba55d3",
            u"Medium Purple | #9370db",
            u"Medium Sea Green | #3cb371",
            u"Medium Slate Blue | #7b68ee",
            u"Medium Spring Green | #00fa9a",
            u"Medium Turquoise | #48d1cc",
            u"Medium Violet Red | #c71585",
            u"Midnight Blue | #191970",
            u"Mint Cream | #f5fffa",
            u"Mistyrose | #ffe4e1",
            u"Moccasin | #ffe4b5",
            u"Navajo White | #ffdead",
            u"Navy | #000080",
            u"Oldlace | #fdf5e6",
            u"Olive | #808000",
            u"Olive Drab | #6b8e23",
            u"Orange | #ffa500",
            u"Orange Red | #ff4500",
            u"Orchid | #da70d6",
            u"Pale Golden Rod | #eee8aa",
            u"Pale Green | #98fb98",
            u"Pale Turquoise | #afeeee",
            u"Pale Violet Red | #db7093",
            u"Papaya Whip | #ffefd5",
            u"Peach Puff | #ffdab9",
            u"Peru | #cd853f",
            u"Pink | #ffc0cb",
            u"Plum | #dda0dd",
            u"Powder Blue | #b0e0e6",
            u"Purple | #800080",
            u"Rebecca Purple | #663399",
            u"Red | #ff0000",
            u"Rosy Brown | #bc8f8f",
            u"Royal Blue | #4169e1",
            u"Saddle Brown | #8b4513",
            u"Salmon | #fa8072",
            u"Sandy Brown | #f4a460",
            u"Sea Green | #2e8b57",
            u"Seashell | #fff5ee",
            u"Sienna | #a0522d",
            u"Silver | #c0c0c0",
            u"Sky Blue | #87ceeb",
            u"Slate Blue | #6a5acd",
            u"Slate grey | #708090",
            u"Snow | #fffafa",
            u"Spring Green | #00ff7f",
            u"Steel Blue | #4682b4",
            u"Tan | #d2b48c",
            u"Teal | #008080",
            u"Thistle | #d8bfd8",
            u"Tomato | #ff6347",
            u"Turquoise | #40e0d0",
            u"Violet | #ee82ee",
            u"Wheat | #f5deb3",
            u"White | #ffffff",
            u"White Smoke | #f5f5f5",
            u"Yellow | #ffff00",
            u"Yellow Green | #9acd32",
        ],
    )


class SettingsEditForm(RegistryEditForm):
    schema = ISettings
    schema_prefix = "collective.frontpage"
    label = _(u"frontpage_settings_title", default=u"Frontpage Settings")


SettingsView = layout.wrap_form(SettingsEditForm, ControlPanelFormWrapper)
