# -*- coding: utf-8 -*-
from collective.frontpage import _
from plone.app.registry.browser.controlpanel import ControlPanelFormWrapper
from plone.app.registry.browser.controlpanel import RegistryEditForm
from plone.z3cform import layout
from zope import schema
from zope.interface import Interface


class ISettings(Interface):

    section_colors = schema.List(
        title=_(u"frontpage_settings_section_colors_title", default="Section Colors"),
        value_type=schema.TextLine(),
        required=True,
        default=[
            u"None | rgba(0,0,0,0)",
            u"Plone Blue | #0083BE",
            u"Dirty White | #F5F5F5",
            u"Semi Transparent | rgba(0,0,0,0.5)",
            u"aliceblue | #f0f8ff",
            u"antiquewhite | #faebd7",
            u"aquamarine | #7fffd4",
            u"azure | #f0ffff",
            u"beige | #f5f5dc",
            u"bisque | #ffe4c4",
            u"black | #000000",
            u"blanchedalmond | #ffebcd",
            u"blue | #0000ff",
            u"blueviolet | #8a2be2",
            u"brown | #a52a2a",
            u"burlywood | #deb887",
            u"cadetblue | #5f9ea0",
            u"chartreuse | #7fff00",
            u"chocolate | #d2691e",
            u"coral | #ff7f50",
            u"cornflowerblue | #6495ed",
            u"cyan/crimson/aqua | #00ffff",
            u"cornsilk | #fff8dc",
            u"darkblue | #00008b",
            u"darkcyan | #008b8b",
            u"darkgoldenrod | #b8860b",
            u"darkgrey | #a9a9a9",
            u"darkgreen | #006400",
            u"darkkhaki | #bdb76b",
            u"darkmagenta | #8b008b",
            u"darkolivegreen | #556b2f",
            u"darkorange | #ff8c00",
            u"darkorchid | #9932cc",
            u"darkred | #8b0000",
            u"darksalmon | #e9967a",
            u"darkseagreen | #8fbc8f",
            u"darkslateblue | #483d8b",
            u"darkslategrey | #2f4f4f",
            u"darkturquoise | #00ced1",
            u"darkviolet | #9400d3",
            u"deeppink | #ff1493",
            u"deepskyblue | #00bfff",
            u"dimgrey | #696969",
            u"dodgerblue | #1e90ff",
            u"firebrick | #b22222",
            u"floralwhite | #fffaf0",
            u"forestgreen | #228b22",
            u"gainsboro | #dcdcdc",
            u"ghostwhite | #f8f8ff",
            u"gold | #ffd700",
            u"goldenrod | #daa520",
            u"grey | #808080",
            u"green | #008000",
            u"greenyellow | #adff2f",
            u"honeydew | #f0fff0",
            u"hotpink | #ff69b4",
            u"indianred | #cd5c5c",
            u"indigo | #4b0082",
            u"ivory | #fffff0",
            u"khaki | #f0e68c",
            u"lavender | #e6e6fa",
            u"lavenderblush | #fff0f5",
            u"lawngreen | #7cfc00",
            u"lemonchiffon | #fffacd",
            u"lightblue | #add8e6",
            u"lightcoral | #f08080",
            u"lightcyan | #e0ffff",
            u"lightgoldenrodyellow | #fafad2",
            u"lightgreen | #90ee90",
            u"lightgrey | #d3d3d3",
            u"lightpink | #ffb6c1",
            u"lightsalmon | #ffa07a",
            u"lightseagreen | #20b2aa",
            u"lightskyblue | #87cefa",
            u"lightslategrey | #778899",
            u"lightsteelblue | #b0c4de",
            u"lightyellow | #ffffe0",
            u"lime | #00ff00",
            u"limegreen | #32cd32",
            u"linen2 | #faf0e6",
            u"magenta/fuchsia | #ff00ff",
            u"maroon | #800000",
            u"mediumaquamarine | #66cdaa",
            u"mediumblue | #0000cd",
            u"mediumorchid | #ba55d3",
            u"mediumpurple | #9370db",
            u"mediumseagreen | #3cb371",
            u"mediumslateblue | #7b68ee",
            u"mediumspringgreen | #00fa9a",
            u"mediumturquoise | #48d1cc",
            u"mediumvioletred | #c71585",
            u"midnightblue | #191970",
            u"mintcream | #f5fffa",
            u"mistyrose | #ffe4e1",
            u"moccasin | #ffe4b5",
            u"navajowhite | #ffdead",
            u"navy | #000080",
            u"oldlace | #fdf5e6",
            u"olive | #808000",
            u"olivedrab | #6b8e23",
            u"orange | #ffa500",
            u"orangered | #ff4500",
            u"orchid | #da70d6",
            u"palegoldenrod | #eee8aa",
            u"palegreen | #98fb98",
            u"paleturquoise | #afeeee",
            u"palevioletred | #db7093",
            u"papayawhip | #ffefd5",
            u"peachpuff | #ffdab9",
            u"peru | #cd853f",
            u"pink | #ffc0cb",
            u"plum | #dda0dd",
            u"powderblue | #b0e0e6",
            u"purple | #800080",
            u"rebeccapurple | #663399",
            u"red | #ff0000",
            u"rosybrown | #bc8f8f",
            u"royalblue | #4169e1",
            u"saddlebrown | #8b4513",
            u"salmon | #fa8072",
            u"sandybrown | #f4a460",
            u"seagreen | #2e8b57",
            u"seashell | #fff5ee",
            u"sienna | #a0522d",
            u"silver | #c0c0c0",
            u"skyblue | #87ceeb",
            u"slateblue | #6a5acd",
            u"slategrey | #708090",
            u"snow | #fffafa",
            u"springgreen | #00ff7f",
            u"steelblue | #4682b4",
            u"tan | #d2b48c",
            u"teal | #008080",
            u"thistle | #d8bfd8",
            u"tomato | #ff6347",
            u"turquoise | #40e0d0",
            u"violet | #ee82ee",
            u"wheat | #f5deb3",
            u"white | #ffffff",
            u"whitesmoke | #f5f5f5",
            u"yellow | #ffff00",
            u"yellowgreen | #9acd32",
        ],
    )


class SettingsEditForm(RegistryEditForm):
    schema = ISettings
    schema_prefix = "collective.frontpage"
    label = _(u"frontpage_settings_title", default=u"Frontpage Settings")


SettingsView = layout.wrap_form(SettingsEditForm, ControlPanelFormWrapper)
